title: "週次進捗報告（第○週）"
labels:
  - weekly
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 基本情報
  - type: input
    id: team-name
    attributes:
      label: チーム名
      placeholder: xxx チーム
    validations:
      required: true
  - type: input
    id: report-date
    attributes:
      label: 報告日
      placeholder: 2025年07月04日
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 📊 定量サマリー
  - type: textarea
    id: kpi-summary
    attributes:
      label: サマリー
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ✅ 進捗状況
  - type: textarea
    id: progress-status
    attributes:
      label: 詳細
    validations:
      required: true
  - type: textarea
    id: team-issues
    attributes:
      label: チームとしての課題・困っていること
    validations:
      required: true
  - type: textarea
    id: team-learning
    attributes:
      label: 今週の学び・気づき
    validations:
      required: true
  - type: textarea
    id: next-week-goals
    attributes:
      label: 次週の予定
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: その他
    validations:
      required: false
