title: "週次進捗報告（第○週）"
labels:
  - weekly
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 基本情報
        以下を記入してください。
  - type: input
    id: team-name
    attributes:
      label: チーム名
      placeholder: xxx チーム
    validations:
      required: true
  - type: input
    id: report-date
    attributes:
      label: 報告日
      placeholder: 2025-07-04
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 📊 定量サマリー
        数字で今週の活動を可視化してください。      
