title: "週次進捗報告（第○週）"
labels:
  - weekly
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 基本情報
        以下を記入してください。
  - type: input
    id: team-name
    attributes:
      label: チーム名
      placeholder: xxx チーム
    validations:
      required: true
