# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  create:
    tags:
      - "v*"
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'env test or production'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script1
        run: |
          echo ${{github.ref}}
          echo ${{inputs.env}}
        
      - name: Run a one-line script2
        run: echo TAG=hoge >> $GITHUB_ENV
        
      - name: Run a one-line script3
        run: | 
          if ${{ github.event_name == 'workflow_dispatch' }} then;
            echo hi
          else
            echo hey
          fi
      
      - name: Run a one-line script
        if: startsWith( github.ref, 'refs/tags/v' )
        run: echo tags

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          if false ; then
            echo first
          elif true; then
            echo second
            sha=${{ github.sha }} && echo ${sha:0:5}
          fi
