name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  create:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      env:
        description: "env test or production"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script1
        run: |
          echo ${{github.ref}}
          echo ${{inputs.env}}
          echo ${{github.event_name}}

      - uses: ./.github/actions/sample
        with:
          module: "client"
          # env: ${{ env.ENV }}
