name: Create Issue from Teams

on:
  workflow_dispatch:
    inputs:
      author:
        description: '投稿者名'
        required: true
      message:
        description: 'メッセージ本文'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const author = '${{ inputs.author }}';
            const message = `${{ inputs.message }}`;
            const issueBody = `
## Teamsからのフィードバック

**投稿者**: ${author}

**内容**:
${message}


---
※このIssueはTeamsからの投稿により自動生成されました。
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Teams投稿 from ${inputs.author}`,
              body: issueBody,
              labels: ['teams']
            });
