name: Create Issue from Teams

on:
  workflow_dispatch:
    inputs:
      author:
        description: '投稿者名'
        required: true
      message:
        description: 'メッセージ本文'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    env:
      AUTHOR: ${{ inputs.author }}
      MESSAGE: ${{ inputs.message }}
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = `
**投稿者**: ${process.env.AUTHOR}

**内容**:
${process.env.MESSAGE}


---
※このIssueはTeamsからの投稿により自動生成されました。
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Teams投稿 from ${inputs.author}`,
              body: issueBody,
              labels: ['teams']
            });
