
name: Wait
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "wait"
        type: environment
        required: true
jobs:
  Part1:
    name: Date
    if: inputs.environment == 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Date
        run: date -u

  Part2:
    needs: Part1
    name: Approve
    if: inputs.environment == 'prod'
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Date
        run: date -u
