name: Caller
on:
  workflow_dispatch:

  push:
    branches:
      - "feature/**"

    paths:
      - "/.github/workflows/workflow-A.yml"
      - "/.github/workflows/workflow-B.yml"

    tags:
      - "test/*"

jobs:
  Set_TAG:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG to GITHUB_ENV
        run: |
          echo github.ref ${{ github.ref }}
           if [[ ${{ github.ref }} =~ refs/heads/ ]]; then
             sha=${{ github.sha }}
             echo "export TAG=${sha:0:6}" >> $GITHUB_ENV
           elif [[ ${{ github.ref }} =~ refs/tags/ ]]; then
             echo "export TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
           fi

  Echo:
    needs: Set_TAG
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          if [ -n "$TAG" ]; then
            echo tag $TAG
          else
            echo "TAG is not defined"
            exit 1
          fi

  # caller-job1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo caller job1-step1!
  #     - run: echo caller job1-step2!
  # Reuse:
  #   uses: ./.github/workflows/workflow-B.yml
  #   with:
  #     env: dev
  # secrets:
  #   sample_secret_key: ${{ secrets.SAMPLE_SECRET_KEY }}
  # caller-job2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo caller job2-step1!
  #     - run: echo caller job2-step2!
