name: Called

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
  #   secrets:
  #     token:
  #       required: true

jobs:
  called-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo called job1-step1!
      - run: echo called job1-step2!
      - run: echo inputs name ${{ inputs.name }}
    #   - uses: actions/labeler@v4
    #     with:
    #       repo-token: ${{ secrets.token }}
    #       configuration-path: ${{ inputs.config-path }}

  called-job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo called job2-step1!
      - run: echo called job2-step2!
