name: Called

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    # secrets:
    #   sample_secret_key:
    #     required: true

jobs:
  # called-job1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo called job1-step1!
  #     - run: echo called job1-step2!
  #     - run: echo inputs name ${{ inputs.name }}
  #     - run: echo secrets.sample_secret_key ${{ secrets.sample_secret_key }}
  #   #   - uses: actions/labeler@v4
  #   #     with:
  #   #       repo-token: ${{ secrets.token }}
  #   #       configuration-path: ${{ inputs.config-path }}

  called-job2:
    runs-on: ubuntu-latest
    steps:
      # - run: echo called job2-step1!
      # - run: echo called job2-step2!

      - name: Set TAG to GITHUB_ENV
        run: |
          if [ ${{ inputs.env }} == 'dev' && startsWith( ${{ github.ref }}, 'refs/heads/' ) ]; then
            sha=${{ github.sha }}
            echo TAG=${sha:0:6} >> $GITHUB_ENV
          elif [ ${{ inputs.env }} == 'dev' && startsWith(  ${{ github.ref }}, 'refs/tags/' ) || ${{ inputs.env }} == 'prod']
            echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
          fi

      - name: echoz
        run: |
          echo ${{ env.TAG }}
